apiVersion: batch/v1
kind: Job
metadata:
  name: atlasadc-job
spec:
  template:
    spec:
      containers:
        - name: atlas-grid-centos7
          image: atlasadc/atlas-grid-centos7
          volumeMounts:
            - name: atlas
              mountPath: /cvmfs/atlas.cern.ch
            - name: atlas-condb
              mountPath: /cvmfs/atlas-condb.cern.ch
            - name: atlas-nightlies
              mountPath: /cvmfs/atlas-nightlies.cern.ch
            - name: sft
              mountPath: /cvmfs/sft.cern.ch
            - name: grid
              mountPath: /cvmfs/grid.cern.ch
            - name: proxy-secret
              mountPath: /proxy
          imagePullPolicy: IfNotPresent
          #resources:
          #  requests:
          #    memory: "1.5Gi"
          command:
            - "sh"
            - "-c"
            - >
              curl -4 https://bootstrap.pypa.io/get-pip.py -o /root/get-pip.py;
              if [ -s /root/get-pip.py ]; then
                 python /root/get-pip.py;
                 pip install requests subprocess32;
              fi;
              echo -e "export computingSite=$computingSite\nexport pandaQueueName=$pandaQueueName\nexport resourceType=$resourceType\nexport proxySecretPath=$proxySecretPath\nexport proxyContent='$proxyContent'\nexport workerID=$workerID\nexport logs_frontend_w=$logs_frontend_w\nexport logs_frontend_r=$logs_frontend_r\n" > /etc/profile.d/job-setup.sh;
              groupadd -g 1308 atlasprd;
              useradd -u 41000 -g 1308 atlasprd;
              su - atlasprd -c "cd /home/atlasprd; curl -4 https://raw.githubusercontent.com/HSF/harvester/flin/pandaharvester/harvestercloud/k8s_startup_script.py -o /home/atlasprd/k8s_startup_script.py; python /home/atlasprd/k8s_startup_script.py";
          securityContext:
            allowPrivilegeEscalation: false

      restartPolicy: Never
      volumes:
        - name: atlas
          persistentVolumeClaim:
            claimName: csi-cvmfs-atlas-pvc
            readOnly: true
        - name: atlas-condb
          persistentVolumeClaim:
            claimName: csi-cvmfs-atlas-condb-pvc
            readOnly: true
        - name: atlas-nightlies
          persistentVolumeClaim:
            claimName: csi-cvmfs-atlas-nightlies-pvc
            readOnly: true
        - name: sft
          persistentVolumeClaim:
            claimName: csi-cvmfs-sft-pvc
            readOnly: true
        - name: grid
          persistentVolumeClaim:
            claimName: csi-cvmfs-grid-pvc
            readOnly: true
        - name: proxy-secret
          secret:
              secretName: proxy-secret
  backoffLimit: 0
